#index:
#    path: /
#    controller: App\Controller\DefaultController::index
hello:
    path: /
    controller: App\Controller\DefaultController::index

category:
    path: /{id}
    controller: App\Controller\DefaultController::category

